### ISSUE TITLE
Task distribution between server nodes

### ISSUE THREAD

**Issue by jd7352** [svt/encore#19]
need help:
       I deployed two Encores, namely` test_server` and `test_node`, in which test_server (192.168.0.1) has `redis`, and pointed the running configuration item redis of test_node (192.168.0.2) to the server, and the two servers share the input and output directories through nfs , when submitting test tasks to both servers, they both work fine.
       The problem now is that when I submit multiple tasks only through the test_server node, these tasks are always queued in the `test_server`, and the `test_node` does not get any tasks, which causes the load to be unbalanced.
      Is my configuration incorrect or something is missing?
      How can we achieve load balancing or polling of tasks among nodes?

The `test_node` run configuration file is as follows:

```
spring:
  redis:
    host: 192.168.0.1
    port: 6379
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

service:
  name: encore_node

encore-settings:
  concurrency: 3
  local-temporary-encode: true
  poll-initial-delay: 1s
  poll-delay: 1s
  audio-mix-presets:
    default:
      pan-mapping:
        6:
          2: stereo|c0=1.0*c0+0.707*c2+0.707*c4|c1=1.0*c1+0.707*c2+0.707*c5
    de:
      fallback-to-auto: false

profile:
  location: https://mydomain/encore/profiles.yml
```
