### ISSUE TITLE
Can we integrate the forward processing of moov in MP4 files?

### ISSUE THREAD

**Issue by jd7352** [svt/encore#24]
Hello everyone：
    Our project has scenarios where HLS playback cannot be used. We use the traditional moov forward shift method to achieve simultaneous playback,

`ffmpeg -i src.mp4 -movflags faststart -c copy dst.mp4`

How can this process be integrated into the Encore process and controlled to be enabled through a profile?

**Comment by fhermansson** [comment]
Yes you can add any param to an output. Here is a simple example for a x264 profile with -movflags faststart:
```
name: faststart
description: Faststart example
encodes:
  - type: X264Encode
    twoPass: false
    suffix: _x264_faststart
    params:
      movflags: faststart
```
